<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.0 setup script
 * Date: Wed, 18 Sep 2013 20:15:55 +0400
 */

$cfg['blowfish_secret'] = '5239d1934d9081.38202916';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['LoginCookieValidity'] = 3600;

?>